language: java
jdk:
 - oraclejdk8
notifications:
 email:
  recipients:
   - guiganister@gmail.com
  on_success: always
before_install:
- gradle check
- cd testfiles
- cd shelltests
- cd config
- bash gitconfiguration.sh
- cd ..
- git config --global user.email "gjcc@cin.ufpe.br"
- git config --global user.name "Guilherme Cavalcanti" 
- sudo apt-get install shunit2
script:
- shunit2 s3mGitTests.sh
- shunit2 s3mBigRepositoryTests.sh
