image: ubuntu:latest

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
    - apt-get update
    - apt-get install -y software-properties-common
    
    - add-apt-repository ppa:webupd8team/java
    - add-apt-repository ppa:git-core/ppa
    - apt-get update
    
    - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
    - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true" | debconf-set-selections
    - apt-get install -y oracle-java8-installer
    
    - apt-get install -y git
    - apt-get install -y libgit2-dev
    
    - export GRADLE_USER_HOME=`pwd`/.gradle

build:
    stage: build
    script:
        - ./gradlew --build-cache assemble
    only:
        - master
        - develop
        - tags
    cache:
        policy: push
        paths:
            - build
            - .gradle

test:
    stage: test
    script:
        - ./gradlew --build-cache check
    only:
        - master
        - develop
        - tags
    cache:
        policy: pull
        paths:
            - build
            - .gradle

